openapi: 3.0.2
info:
  title: Accounts Service
  description: Services to support accounts data
  version: 0.0.1
paths:
  /accounts:
    get:
      tags:
        - accounts
      summary: Retrieves account objects
      operationId: findAllAccounts
      parameters:
        - $ref: 'common-spec.yaml#/components/parameters/page'
        - $ref: 'common-spec.yaml#/components/parameters/limit'
      responses:
        200:
          description: Successfully get objects
          content:
            application/json:
              schema:
                type: array
                description: Found account objects
                items:
                  $ref: '#/components/schemas/Account'
        default:
          $ref: 'common-spec.yaml#/components/responses/Error'
    post:
      tags:
        - accounts
      summary: Adds a new account
      operationId: addAccount
      requestBody:
        description: Account object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
        required: true
      responses:
        201:
          description: Created account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          $ref: 'common-spec.yaml#/components/responses/InvalidInput'
        default:
          $ref: 'common-spec.yaml#/components/responses/Error'
  /accounts/{accountId}:
    get:
      tags:
        - accounts
      summary: Retrieves a single account by id
      operationId: findAccountById
      parameters:
        - $ref: '#/components/parameters/accountId'
      responses:
        200:
          description: An account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          $ref: 'common-spec.yaml#/components/responses/NotFound'
        default:
          $ref: 'common-spec.yaml#/components/responses/Error'
    patch:
      tags:
        - accounts
      summary: Updates an account
      operationId: updateAccount
      parameters:
        - $ref: '#/components/parameters/accountId'
      requestBody:
        description: Fields to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccount'
        required: true
      responses:
        204:
          description: Updated
          content: {}
        404:
          $ref: 'common-spec.yaml#/components/responses/NotFound'
        default:
          $ref: 'common-spec.yaml#/components/responses/Error'
    delete:
      tags:
        - accounts
      summary: Deletes an account
      operationId: deleteAccount
      parameters:
        - $ref: '#/components/parameters/accountId'
      responses:
        204:
          description: Deleted
          content: {}
        404:
          $ref: 'common-spec.yaml#/components/responses/NotFound'
        default:
          $ref: 'common-spec.yaml#/components/responses/Error'
components:
  schemas:
    AccountId:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          description: Unique account ID
          format: int64
    AccountProperties:
      required:
        - name
        - email
        - balance
      type: object
      properties:
        name:
          type: string
          description: Name of the customer
          example: John
        email:
          type: string
          description: Email
          example: johnsnow@thewall.com
        balance:
          type: number
          description: Customer balance in USD
          example: 150.00
    Account:
      allOf:
        - $ref: '#/components/schemas/AccountId'
        - $ref: '#/components/schemas/AccountProperties'
    CreateAccount:
      allOf:
        - $ref: '#/components/schemas/AccountProperties'
    UpdateAccount:
      type: object
      properties:
        name:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        balance:
          nullable: true
          type: number
  parameters:
    accountId:
      name: accountId
      in: path
      description: Account ID
      required: true
      schema:
        type: integer
        format: int64
